# The following tag is to get correct syntax highlighting for this file in vim text editor
# vim: syntax=spec

Name:       {{{ git_dir_name }}}
Version:    {{{ git_dir_version }}}
Release:    1%{?dist}
Summary:    notepadqq
License:    GPLv3
URL:        https://github.com/notepadqq/notepadqq

# Detailed information about the source Git repository and the source commit
# for the created rpm package
VCS:        {{{ git_dir_vcs }}}

# git_dir_pack macro places the repository content (the source files) into a tarball
# and returns its filename. The tarball will be used to build the rpm.
Source:     {{{ git_dir_pack }}}

#Packages required for build
BuildRequires: cargo
%{?systemd_requires}
BuildRequires: qt5-qtbase-devel
BuildRequires: qt5-qttools-devel
BuildRequires: qt5-qtwebengine-devel 
BuildRequires: qt5-qtwebsockets-devel 
BuildRequires: qt5-qtsvg-devel 
BuildRequires: uchardet 
BuildRequires: qt5-qtwebchannel-devel 
BuildRequires: pkgconfig

#Packages required to work
#Requires: dbus-common 
#Requires: systemd

# More detailed description of the package
%description
notepadqq

%define debug_package %{nil}

#--
%prep


# This will invoke `make` command in the directory with the extracted sources.
%build
./configure --prefix /usr
make

# This will copy the files generated by the `make` command above into
# the installable rpm package.
%install

make install

# do after installation
%post

# do before uninstallation
%preun


# do after unistallation
%postun


# Changelog
%changelog
{{{ git_dir_changelog }}}
